### 課題4-1

#### 1. 一人分の同時分布

確率変数の定義域を以下のように定める
$
h \in {R_A, R_B,R_{AB}, R_O}
\ $, $
g \in {aa, ao, bb, bo, ab, oo}
$,

このとき、一人分の同時分布は

$$
p(h,g;\boldsymbol\theta) = \begin{cases}
    \theta_A^2 & (h=R_A, g=aa) \\
    2\theta_A\theta_O & (h=R_A, g=ao) \\
    \theta_B^2 & (h=R_B, g=bb) \\
    2\theta_B\theta_O & (h=R_B, g=bo) \\
    2\theta_A\theta_B & (h=R_{AB}, g=ab) \\
    \theta_O^2 & (h=R_O, g=oo) \\
    0 & (\text{otherwise})
  \end{cases}
$$

図で示すとわかりやすく、その場合は以下のようになる。

| h\g | aa | ao | bb | bo | ab | oo |
|:-----------|:------------:|:------------:|:-----------:|:------------:|:------------:|:------------:|
| $R_A$ | $\theta_A^2$ | $2\theta_A\theta_O$ | 0 | 0 | 0 | 0 |
| $R_B$  | 0 | 0 | $\theta_B^2$ | $2\theta_B\theta_O$ | 0 | 0 |
| $R_{AB}$ | 0 | 0 | 0 | 0 | $2\theta_A\theta_B$ | 0 |
| $R_O$ | 0 | 0 | 0 | 0 | 0 |$\theta_O^2$|



#### 2. i番目の人について、$h_i, g_i$としたときに、すべての人に対して、全確率変数の同時分布を求める

尤度を求めるようなもの。ここで、gの取りうるすべてに対して、その人数を$\{N_{aa},N_{ao},N_{bb},N_{bo},N_{ab},N_{oo}\}$とする。また、全体でN人いるとおく。これを用いると、回答は以下のようになる。

$$
p({\bf h},{\bf g} ; \boldsymbol{\theta}) = \frac{N!}{N_{aa}！N_{ao}！N_{bb}！N_{bo}！N_{ab}！N_{oo}！} (\theta_A^2)^{N_{aa}}(2\theta_A\theta_O)^{N_{ao}}(\theta_B^2)^{N_{bb}}(2\theta_B\theta_O)^{N_{bo}}(2\theta_A\theta_B)^{N_{ab}}(\theta_O^2)^{N_{oo}}
$$


#### 3. EMアルゴリズムの更新式

2の式に対して負の対数を取ると

$$
-\log(p({\bf h},{\bf g} ; \boldsymbol{\theta})) = -\left\{\log(\frac{N!}{N_{aa}！N_{ao}！N_{bb}！N_{bo}！N_{ab}！N_{oo}！}) + N_{aa}\log(\theta_A^2) + N_{ao}\log(2\theta_A\theta_O) + N_{bb} \log(\theta_B^2) + N_{bo}\log(2\theta_B\theta_O) + N_{ab}\log(2\theta_A\theta_B) + N_{oo}\log(\theta_O^2)\right\}
$$

となる。これについて、$p({\bf g} | {\bf h} ; \boldsymbol \theta)$で平均を取りたいが、この分布を陽に計算することは困難である。そこでもう少し式変形をしてみる。

$$
\left< -\log(p({\bf h},{\bf g} ; \boldsymbol{\theta}))\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}= 
-\left\{
\left< \log(\frac{N!}{N_{aa}！N_{ao}！N_{bb}！N_{bo}！N_{ab}！N_{oo}！}) \right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}\\
+\left< N_{aa}\log(\theta_A^2) \right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\left<  N_{ao}\log(2\theta_A\theta_O) \right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)} 
+\left< N_{bb} \log(\theta_B^2)\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\left< N_{bo}\log(2\theta_B\theta_O)\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\left< N_{ab}\log(2\theta_A\theta_B)\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\left< N_{oo}\log(\theta_O^2)\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}\right\}
$$


$$
\left< -\log(p({\bf h},{\bf g} ; \boldsymbol{\theta}))\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}= 
-\left\{
\left< \log(\frac{N!}{N_{aa}！N_{ao}！N_{bb}！N_{bo}！N_{ab}！N_{oo}！}) \right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}\\
+\log(\theta_A^2)\left< N_{aa} \right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\log(2\theta_A\theta_O) \left< N_{ao}\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)} 
+\log(\theta_B^2)\left< N_{bb}\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\log(2\theta_B\theta_O)\left< N_{bo}\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\log(2\theta_A\theta_B)\left< N_{ab}\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}
+\log(\theta_O^2)\left< N_{oo}\right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}\right\}
$$

ここで、$\left< N_{aa} \right>_{p({\bf g} | {\bf h} ; \boldsymbol \theta)}$ 等は観測データと現在のパラメーターより、以下のようにわかる。
EMalgorithmで扱うiterationの添字を右型にカッコつきで書く。 k th iterationではその時のパラメーターを用いて以下のように、書くことができる。

$$
N_{aa}^{(k)} = NR_A \frac{\theta_A^{(k)^2}}{\theta_A^{(k)^2} + 2\theta_A^{(k)^2}\theta_O^{(k)^2}} \\
N_{ao}^{(k)} = NR_A \frac{2\theta_A^{(k)^2}\theta_O^{(k)^2}}{\theta_A^{(k)^2} + 2\theta_A^{(k)^2}\theta_O^{(k)^2}} \\
N_{bb}^{(k)} = NR_B \frac{\theta_B^{(k)^2}}{\theta_B^{(k)^2} + 2\theta_B^{(k)^2}\theta_O^{(k)^2}} \\
N_{bo}^{(k)} = NR_B \frac{2\theta_B^{(k)^2}\theta_O^{(k)^2}}{\theta_B^{(k)^2} + 2\theta_B^{(k)^2}\theta_O^{(k)^2}} \\
N_{ab} = NR_{AB} \\
N_{oo} = NR_O
$$

これがいわゆるE-stepである。

M-stepの更新は$N_{aa}^{(k)}$等を固定して、以下の損失関数を最小化する$\theta_A, \theta_B, \theta_O$を$\theta_A^{(k+1)}, \theta_B^{(k+1)}, \theta_O^{(k+1)}$とする。

$$
loss(\theta_A, \theta_B, \theta_O)= 
-\left\{
\log(\theta_A^2)N_{aa}^{(k)}
+\log(2\theta_A\theta_O) N_{ao}^{(k)}
+\log(\theta_B^2) N_{bb}^{(k)}
+\log(2\theta_B\theta_O) N_{bo}^{(k)}
+\log(2\theta_A\theta_B)N_{ab}
+\log(\theta_O^2)N_{oo}\right\}
$$

(最小化の上ではNは必要ないのでNが与えられなくてもthetaを計算できる)

#### 4. $\theta$を最尤解を求める
M-stepに関しては勾配法で損失関数を最小化する$\theta$を見つける

In [1]:
import torch
torch.manual_seed(2019)
theta=torch.rand(2, requires_grad=True)
Ra,Rb,Rab,Ro=0.4,0.2,0.1,0.3

def expectation(t_a,t_b,t_o):
    Naa=Ra*((t_a**2)/(2*t_a*t_o + t_a**2))
    Nao=Ra*((2*t_a*t_o)/(2*t_a*t_o + t_a**2))
    Nbb=Rb*((t_b**2)/(2*t_b*t_o + t_b**2))
    Nbo=Rb*((2*t_b*t_o)/(2*t_b*t_o + t_b**2))
    Nab=Rab;Noo=Ro
    return [Naa,Nao,Nbb,Nbo,Nab,Noo]

def loss_fn(t_a,t_b,t_o, Ns):
    Naa,Nao,Nbb,Nbo,Nab,Noo =Ns
    return -(Naa*torch.log(t_a**2)+Nao*torch.log(2*t_a*t_o)
            +Nbb*torch.log(t_b**2)+Nbo*torch.log(2*t_b*t_o)
            +Nab*torch.log(2*t_a*t_b)+Noo*torch.log(t_o**2))

def argmin(theta,Ns,lr=0.01,n_epochs=1000):
    for e in range(n_epochs):
        #損失関数の定義
        loss=loss_fn(theta[0],theta[1],(1-theta[0]-theta[1]), Ns)
        # SGDで最適化
        loss.backward()
        with torch.no_grad():
            theta=theta - lr*theta.grad
        theta.requires_grad_()
        return theta

In [2]:
for iloop in range(100):
    #E-step
    Ns=expectation(theta[0],theta[1],(1-theta[0]-theta[1]))
    
    #M-step
    theta=argmin(theta,Ns)
    
    if iloop % 10 ==0:
        print(theta)

print('\ntheta_a:{}\ntheta_b:{}\ntheta_o:{}'.format(theta[0],theta[1],(1-theta[0]-theta[1])))

tensor([0.2519, 0.5308], requires_grad=True)
tensor([0.1877, 0.3039], requires_grad=True)
tensor([0.2060, 0.1990], requires_grad=True)
tensor([0.2222, 0.1563], requires_grad=True)
tensor([0.2310, 0.1443], requires_grad=True)
tensor([0.2349, 0.1414], requires_grad=True)
tensor([0.2364, 0.1407], requires_grad=True)
tensor([0.2371, 0.1404], requires_grad=True)
tensor([0.2373, 0.1403], requires_grad=True)
tensor([0.2374, 0.1403], requires_grad=True)

theta_a:0.2374424934387207
theta_b:0.14026571810245514
theta_o:0.6222918033599854


In [29]:
theta

tensor([0.2247, 0.4733], requires_grad=True)

$$
loss(\theta_A, \theta_B, \theta_O) = -\log(\Gamma(N_{aa}+1))-\log(\Gamma(N_{ao}+1))-\log(\Gamma(N_{bb}+1))-\log(\Gamma(N_{bo}+1))-\log(\Gamma(N_{ab}+1))-\log(\Gamma(N_{oo}+1)) \\ + N_{aa}\log(\theta_A^2) + N_{ao}\log(2\theta_A\theta_O) + N_{bb} \log(\theta_B^2) + N_{bo}\log(2\theta_B\theta_O) + N_{ab}\log(2\theta_A\theta_B) + N_{oo}\log(\theta_O^2)
$$

別解、$N_aa$等を$theta$に関する関数だと解釈して、勾配法で2の負の対数尤度を最小化する。
ただしNについて答えが変化するので、Nを日本の人口である($10^8$で実験を行った。)

損失関数
$$
loss(\theta_A, \theta_B, \theta_O) = -\log(\Gamma(N_{aa}+1))-\log(\Gamma(N_{ao}+1))-\log(\Gamma(N_{bb}+1))-\log(\Gamma(N_{bo}+1))-\log(\Gamma(N_{ab}+1))-\log(\Gamma(N_{oo}+1)) \\ - N_{aa}\log(\theta_A^2) - N_{ao}\log(2\theta_A\theta_O) - N_{bb} \log(\theta_B^2) - N_{bo}\log(2\theta_B\theta_O) - N_{ab}\log(2\theta_A\theta_B) - N_{oo}\log(\theta_O^2)
$$

実装上においてはガンマ関数をスターリングの近似を用いて以下のように定義した。

$$

$$

別解、$N_aa$等を$theta$に関する関数だと解釈して、勾配法で2の負の対数尤度を最小化する。
ただしNについて答えが変化するので、Nを日本の人口である($10^8$で実験を行った。)

損失関数
$$
loss(\theta_A, \theta_B, \theta_O) = -\log(\Gamma(N_{aa}+1))-\log(\Gamma(N_{ao}+1))-\log(\Gamma(N_{bb}+1))-\log(\Gamma(N_{bo}+1))-\log(\Gamma(N_{ab}+1))-\log(\Gamma(N_{oo}+1)) \\ + N_{aa}\log(\theta_A^2) + N_{ao}\log(2\theta_A\theta_O) + N_{bb} \log(\theta_B^2) + N_{bo}\log(2\theta_B\theta_O) + N_{ab}\log(2\theta_A\theta_B) + N_{oo}\log(\theta_O^2)
$$

実装上においてはガンマ関数をスターリングの近似を用いて以下のように定義した。

$$

$$

In [9]:
import torch

$\theta_a$,
$\theta_b$,
をthetaとおく。ただし$\theta_o$=(1-$\theta_a$-$\theta_b$)

In [17]:
torch.lgamma(theta)

tensor([2.9203, 3.6476], grad_fn=<LgammaBackward>)

In [14]:
# torch.manual_seed(2019)
torch.manual_seed(2000)
theta=torch.rand(2, requires_grad=True)
Ra,Rb,Rab,Ro=0.4,0.2,0.1,0.3

def log_likelyhood(t_a,t_b,t_o):
    Naa=Ra*((t_a**2)/(2*t_a*t_o + t_a**2))
    Nao=Ra*((2*t_a*t_o)/(2*t_a*t_o + t_a**2))
    Nbb=Rb*((t_b**2)/(2*t_b*t_o + t_b**2))
    Nbo=Rb*((2*t_b*t_o)/(2*t_b*t_o + t_b**2))
    Nab=Rab;Noo=Ro
    torch.ga
    return -(Naa*torch.log(t_a**2)+Nao*torch.log(2*t_a*t_o)
            +Nbb*torch.log(t_b**2)+Nbo*torch.log(2*t_b*t_o)
            +Nab*torch.log(2*t_a*t_b)+Noo*torch.log(t_o**2))

In [7]:
lr=0.001
for epoch in range(1000):
    #損失関数の定義
    t_a,t_b=theta
    loss=log_likelyhood(theta[0],theta[1],(1-theta[0]-theta[1]))    
    
    # SGDで最適化
    loss.backward()
    with torch.no_grad():
        theta=theta - lr*theta.grad

    theta.requires_grad_()
    
    if epoch%100==0:
        print(theta)

tensor([0.0678, 0.0457], requires_grad=True)
tensor([0.2021, 0.1365], requires_grad=True)
tensor([0.2255, 0.1420], requires_grad=True)
tensor([0.2329, 0.1414], requires_grad=True)
tensor([0.2357, 0.1408], requires_grad=True)
tensor([0.2368, 0.1405], requires_grad=True)
tensor([0.2372, 0.1404], requires_grad=True)
tensor([0.2374, 0.1403], requires_grad=True)
tensor([0.2374, 0.1403], requires_grad=True)
tensor([0.2374, 0.1403], requires_grad=True)


In [8]:
print('theta_a:{}\ntheta_b:{}\ntheta_o:{}'.format(theta[0],theta[1],(1-theta[0]-theta[1])))

theta_a:0.2374601662158966
theta_b:0.14025960862636566
theta_o:0.6222802400588989
