In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd
import joblib

In [2]:
df=pd.read_csv('./data/feature_dataframe.csv',index_col=0)
df.head()

0         1         2         3         4         5         6  \
0 -0.273399 -0.080405  0.525637 -0.069822 -0.065952 -0.362005 -0.252148   
1 -0.225062  0.230627 -0.014016 -0.351334  0.583346  0.130343 -0.205661   
2 -0.223140 -0.182229  0.198964 -0.587038  0.116019 -0.355480  0.262283   
3 -1.227587 -0.311005  0.324756 -0.160096  0.181778 -0.603752 -0.114064   
4 -0.120004 -0.082054  0.300280 -0.222195 -0.244158 -0.212468 -0.102699   

          7         8         9  ...       759       760       761       762  \
0  0.907441 -0.175653 -0.556349  ... -0.342327  0.156985 -0.538675  0.222728   
1  0.058135 -0.066915  0.191623  ... -0.531517  0.002541 -0.579783 -0.195158   
2  0.356748 -0.127987 -0.393936  ...  0.017393  0.444674 -0.586118 -0.224009   
3  0.098340 -0.080799 -0.143739  ... -0.105906  0.331748 -0.793930  0.545979   
4  0.087957 -0.012975  0.055390  ... -0.051777  0.364250 -0.179219  0.360928   

        763       764       765       766       767       category  
0  0.366792 -0.314745 -0.492801  0.488872  0.257185           tech  
1  0.285872 -0.190588  0.293731  0.692671  0.257362       business  
2  0.283355  0.007049  0.238280  0.607918  0.583781          sport  
3  0.334995 -0.424954 -0.544916  0.642600  0.270558          sport  
4  0.586258 -0.214748 -0.392782  0.688578  0.205861  entertainment  

[5 rows x 769 columns]

In [3]:
target=df['category'].values
data=df.drop('category',axis=1).values

In [4]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier

In [5]:
cv=StratifiedKFold(n_splits=5,shuffle=True,random_state=2019)

In [6]:
clf=RandomForestClassifier(n_estimators=1000,n_jobs=2,random_state=1)
result=cross_val_score(clf,data,target,cv=cv,n_jobs=1,verbose=2)
print(result,result.mean())

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  ................................................................
[CV] ................................................. , total=  18.7s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   18.8s remaining:    0.0s


[CV] ................................................. , total=  16.9s
[CV]  ................................................................
[CV] ................................................. , total=  18.9s
[CV]  ................................................................
[CV] ................................................. , total=  18.1s
[CV]  ................................................................
[CV] ................................................. , total=  17.2s
[0.93526786 0.95730337 0.95720721 0.95720721 0.95945946] 0.9532890203606496


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  1.5min finished


In [7]:
clf=LogisticRegression(solver='newton-cg',multi_class='multinomial',random_state=1)
result=cross_val_score(clf,data,target,cv=cv,n_jobs=1,verbose=2)
print(result,result.mean())

[CV]  ................................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................................................. , total=   1.5s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.6s remaining:    0.0s


[CV] ................................................. , total=   2.1s
[CV]  ................................................................
[CV] ................................................. , total=   1.9s
[CV]  ................................................................
[CV] ................................................. , total=   2.1s
[CV]  ................................................................
[CV] ................................................. , total=   1.7s
[0.95535714 0.98426966 0.95945946 0.96846847 0.97297297] 0.9681055413358785


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    9.3s finished


In [8]:
clf=ExtraTreesClassifier(n_estimators=1000,n_jobs=2,random_state=2)
result=cross_val_score(clf,data,target,cv=cv,verbose=2)
print(result,result.mean())

[CV]  ................................................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................................................. , total=   7.0s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.0s remaining:    0.0s


[CV] ................................................. , total=   6.8s
[CV]  ................................................................
[CV] ................................................. , total=   6.3s
[CV]  ................................................................
[CV] ................................................. , total=   6.3s
[CV]  ................................................................
[CV] ................................................. , total=   6.5s
[0.94419643 0.95730337 0.95945946 0.95945946 0.96171171] 0.9564260859977154


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:   33.1s finished


一応今回のロジスティック回帰の結果は、判別を試みていたkaggleのカーネルの中では一番精度がよい
https://www.kaggle.com/yufengdev/bbc-fulltext-and-category